language: node_js

script:
 - npm run build

before_install:
 - chmod +x node_modules/.bin/webpack
 - chmod +x deploy.sh
 - npm install -g uglify-es uglify-js

after_success:
 - ./deploy.sh

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: out
  on:
    branch: master

branches:
  only:
  - master

git:
  depth: 3